package com.livefront.sealedenum

/**
 * An interface providing `Enum`-like methods in a generic manner, for sealed classes that only have objects as
 * subclasses.
 *
 * Object implementations for [SealedEnum] will automatically be generated by annotating the sealed class's companion
 * object with [GenSealedEnum]. Additionally, an implementation of [SealedEnum] can be created for a normal `Enum` with
 * [createSealedEnumFromEnum].
 */
public interface SealedEnum<T> : Comparator<T> {

    /**
     * A list of all [T] objects.
     */
    public val values: List<T>

    /**
     * Returns the index of [obj] in the [values] list.
     */
    public fun ordinalOf(obj: T): Int

    /**
     * Returns the name of [obj] for use with [valueOf].
     */
    public fun nameOf(obj: T): String

    /**
     * Returns the [T] object for the given [name].
     *
     * If the given name doesn't correspond to any [T], an [IllegalArgumentException] will be thrown.
     */
    public fun valueOf(name: String): T

    public override fun compare(first: T, second: T): Int = ordinalOf(first) - ordinalOf(second)
}

/**
 * Creates a [SealedEnumWithEnumProvider] for the enum [E].
 */
public inline fun <reified E : Enum<E>> createSealedEnumFromEnum(): SealedEnumWithEnumProvider<E, E> =
    createSealedEnumFromEnumArray(enumValues(), E::class.java)

/**
 * Creates a [SealedEnumWithEnumProvider] for the enum [E] with the given array of enum values.
 */
public fun <E : Enum<E>> createSealedEnumFromEnumArray(
    values: Array<E>,
    enumClass: Class<E>
): SealedEnumWithEnumProvider<E, E> = object : SealedEnumWithEnumProvider<E, E> {
    val nameToValueMap: Map<String, E> by lazy(LazyThreadSafetyMode.PUBLICATION) {
        values.associateBy { it.name }
    }

    override val enumClass: Class<E> = enumClass

    override val values: List<E> = values.toList()

    override fun ordinalOf(obj: E): Int = obj.ordinal

    override fun nameOf(obj: E): String = obj.name

    override fun valueOf(name: String): E =
        nameToValueMap[name] ?: throw IllegalArgumentException("No sealed enum constant $name")

    /**
     * Isomorphism is given by the identity function
     */
    override fun sealedObjectToEnum(obj: E): E = obj

    /**
     * Isomorphism is given by the identity function
     */
    override fun enumToSealedObject(enum: E): E = enum
}
