complexity:
  CyclomaticComplexMethod:
    excludes: [ '**/generated/**' ]

empty-blocks:
  EmptyDefaultConstructor:
    excludes: [ '**/generated/**' ]

formatting:
  ArgumentListWrapping:
    excludes: [ '**/generated/**' ]
  EnumEntryNameCase:
    excludes: [ '**/generated/**' ]
  Filename:
    excludes: [ '**/generated/**' ]
  Indentation:
    excludes: [ '**/generated/**' ]
  MaximumLineLength:
    excludes: [ '**/generated/**', '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  NoConsecutiveBlankLines:
    excludes: ['**/generated/**' ]
  NoLineBreakBeforeAssignment:
    excludes: [ '**/generated/**' ]
  SpacingAroundCurly:
    excludes: [ '**/generated/**' ]
  Wrapping:
    excludes: [ '**/generated/**' ]

naming:
  ClassNaming:
    excludes: [ '**/generated/**' ]
  MatchingDeclarationName:
    excludes: [ '**/generated/**' ]
  TopLevelPropertyNaming:
    excludes: ['**/generated/**', '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']

style:
  ForbiddenComment:
    values: ['FIXME:', 'STOPSHIP:']
  MagicNumber:
    excludes: [ '**/generated/**', '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**'  ]
  MaxLineLength:
    excludes: [ '**/generated/**', '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
